name: CI

on:
  # Run on any push to main (includes when a PR is completed)
  push:
    branches: [main]

  # Run on all PRs targeted at main
  pull_request:
    branches: [main]

  # Allows this workflow to be manually run from the GitHub Actions tab
  workflow_dispatch:

jobs:
  build_and_test:
    name: Build and Test
    runs-on: ubuntu-latest
    outputs:
      testResults: ${{ steps.test.outcome }}
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE so job can access it
      - uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v1

      - name: Install dependencies
        run: npm i

      - name: Build App
        run: npm run build

      - name: Test App
        id: test
        run: npm run test
  comment_suggestions:
    name: Comment slash commnds on failure
    runs-on: ubuntu-latest
    needs: build_and_test
    if: ${{ failure() && needs.build_and_test.outputs.testResults == 'failure' }}
    steps:
      - name: Comment helpful slash command
        uses: actions/github-script@v3
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: 'I see the tests failed - did you know you can comment `/update-snaps` to automatically update the jest snapshots 🎉'
            })
